### ISSUE TITLE
Color change to yellow for Jac P thijsse Students

### ISSUE THREAD

**Issue by Vector04** [wilco375/RoosterNotification#2]
When using the app as a Jac. P. Thijsse College student, the themecolor of the app changes from blue to yellow.
It would be great if this feature would be removed, I do not understand why this color change should be intended behaviour, especially since blue does look better.

**Comment by wilco375** [comment]
This is because the theme color of your school is green-yellow-ish.

**Comment by Vector04** [comment]
See https://www.jpthijsse.nl/. I do wonder why you choose yellow a the theme color....
